//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aukcionas
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AukcionasEntities : DbContext
    {
        public AukcionasEntities()
            : base("name=AukcionasEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Aukcionas> Aukcionas { get; set; }
        public virtual DbSet<Dailininkas> Dailininkas { get; set; }
        public virtual DbSet<Kolekcionierius> Kolekcionierius { get; set; }
        public virtual DbSet<Paveikslas> Paveikslas { get; set; }
    }
}
