//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aukcionas
{
    using System;
    using System.Collections.Generic;
    
    public partial class Paveikslas
    {
        public int PaveiksloID { get; set; }
        public Nullable<int> SavininkoID { get; set; }
        public System.DateTime Metai { get; set; }
        public int Kaina { get; set; }
        public string DailininkoVardas { get; set; }
        public string DailininkoPavarde { get; set; }
        public string AukcionoPavadinimas { get; set; }
    
        public virtual Aukcionas Aukcionas { get; set; }
        public virtual Dailininkas Dailininkas { get; set; }
        public virtual Kolekcionierius Kolekcionierius { get; set; }
    }
}
